[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python backend/app.py"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
startTimeout = 600

[env]
PORT = "5000"
PYTHON_VERSION = "3.10"
